require 'rails_helper'

RSpec.describe UploadsController, :type => :controller do

  let(:upload_file) { fixture_file_upload('files/example_input.tab', 'text/tab-separated-values') }

  # Autogenerated from scaffolding
  describe "GET index" do
    it "assigns all uploads as @uploads" do
      upload = Upload.create!
      get :index, {}
      expect(assigns(:uploads)).to eq([upload])
    end
  end
  
  # Autogenerated from scaffolding
  describe "GET show" do
    it "assigns the requested upload as @upload" do
      upload = Upload.create!
      get :show, {:id => upload.to_param}
      expect(assigns(:upload)).to eq(upload)
    end
  end

  describe "POST create" do

    context "when given a file" do
      subject { -> { post :create, upload_file: upload_file } }

      it { should change(Upload, :count).by(1) }
      it { should change(Purchaser, :count).by(3) }
      it { should change(Merchant, :count).by(3) }
      it { should change(PurchasedItem, :count).by(4) }
    end

    context "when not given a file" do
      it "should render the new template" do
        post :create, {}
        expect(response).to render_template(:new)
      end
    end
  end

  # Autogenerated from scaffolding
  describe "DELETE destroy" do
    it "destroys the requested upload" do
      upload = Upload.create!
      expect {
        delete :destroy, {:id => upload.to_param}
      }.to change(Upload, :count).by(-1)
    end

    it "redirects to the uploads list" do
      upload = Upload.create!
      delete :destroy, {:id => upload.to_param}
      expect(response).to redirect_to(uploads_url)
    end
  end
end
